
CREATE TABLE IF NOT EXISTS CONAGUA_PRONOSTICO.API_PRONOSTICO_CONAGUA_MX.PRONOSTICO_MUNICIPIOS (
    id_municipio INTEGER,
    nombre_municipio VARCHAR(255),
    dia_local VARCHAR(255),
    temperatura_maxima_promedio NUMERIC,
    temperatura_minima_promedio NUMERIC,
    precipitacion_promedio NUMERIC,
    temperatura_promedio NUMERIC,
    INSERTD_AT TIMESTAMP_TZ
);

CREATE TABLE IF NOT EXISTS CONAGUA_PRONOSTICO.API_PRONOSTICO_CONAGUA_MX.AIRFLOW_TASK_LOGS  (
    DAG VARCHAR(255),
    TASK VARCHAR(255),
    LAST_TIMESTAMP TIMESTAMP_NTZ,
    STATE VARCHAR(50),
    EXCEPTION TEXT,
    OWNER VARCHAR(255),
    FINISHED_AT TIMESTAMP_NTZ,
    DURATION FLOAT,
    OPERATOR VARCHAR(255),
    CRON VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS CONAGUA_PRONOSTICO.API_PRONOSTICO_CONAGUA_MX.DATA_MUNICIPIOS 
(
Cve_Ent INTEGER,
Cve_Mun INTEGER,
Value INTEGER

);

TRUNCATE TABLE CONAGUA_PRONOSTICO.API_PRONOSTICO_CONAGUA_MX.DATA_MUNICIPIOS ;

CREATE TABLE IF NOT EXISTS CONAGUA_PRONOSTICO.API_PRONOSTICO_CONAGUA_MX.DATA_PRONOSTICO_MUNICIPIO(
    CVE_ENT INT,
    CVE_MUN INT,
    NOMBRE_MUNICIPIO VARCHAR,
    TEMPERATURA_MAXIMA_PROMEDIO FLOAT,
    TEMPERATURA_MINIMA_PROMEDIO FLOAT,
    PRECIPITACION_PROMEDIO FLOAT,
    TEMPERATURA_PROMEDIO FLOAT,
    VALUE FLOAT,
    INSERTD_AT TIMESTAMP_TZ
);

TRUNCATE TABLE CONAGUA_PRONOSTICO.API_PRONOSTICO_CONAGUA_MX.DATA_PRONOSTICO_MUNICIPIO ;


CREATE TABLE IF NOT EXISTS CONAGUA_PRONOSTICO.API_PRONOSTICO_CONAGUA_MX.SERVICE_PRONOSTICO_AUDIT(
    ID	NUMBER,
    REGISTROS_INSERTADOS NUMBER,
    TIEMPO_DURACION	NUMBER,
    FECHA_INICIO TIMESTAMP_NTZ(9),
    FECHA_FINALIZACION TIMESTAMP_NTZ(9),
    NOMBRE_TABLA VARCHAR(255),
    BASE_DE_DATOS VARCHAR(255),
    ESQUEMA	VARCHAR(255)
);