INSERT INTO CONAGUA_PRONOSTICO.API_PRONOSTICO_CONAGUA_MX.DATA_PRONOSTICO_MUNICIPIO (
    CVE_ENT,
    CVE_MUN,
    NOMBRE_MUNICIPIO,
    PRECIPITACION_PROMEDIO,
    TEMPERATURA_PROMEDIO,
    VALUE,
    INSERTD_AT
)
SELECT distinct
    dm.CVE_ENT,
    dm.CVE_MUN,
    p2.NOMBRE_MUNICIPIO,
    p2.PRECIPITACION_PROMEDIO,
    p2.TEMPERATURA_PROMEDIO,
    dm.VALUE,
    CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) AS insertd_at
FROM
    CONAGUA_PRONOSTICO.API_PRONOSTICO_CONAGUA_MX.DATA_MUNICIPIOS dm
INNER JOIN
    CONAGUA_PRONOSTICO.API_PRONOSTICO_CONAGUA_MX.PRONOSTICO_MUNICIPIOS p2
ON
    dm.CVE_MUN = p2.ID_MUNICIPIO
WHERE
    dm.CVE_ENT = (SELECT max(DATE_PART('DAY', dia_local::date)) FROM CONAGUA_PRONOSTICO.API_PRONOSTICO_CONAGUA_MX.PRONOSTICO_MUNICIPIOS)
;