CREATE DATABASE IF NOT EXISTS CONAGUA_PRONOSTICO;
CREATE SCHEMA IF NOT EXISTS API_PRONOSTICO_CONAGUA_MX;
USE CONAGUA_PRONOSTICO.API_PRONOSTICO_CONAGUA_MX;


--tabla maestra permisos de administrador
CREATE TABLE IF NOT EXISTS CONAGUA_PRONOSTICO.API_PRONOSTICO_CONAGUA_MX.SERVICE_PRONOSTICO_POR_MUNICIPIOS_GZ (
    desciel VARCHAR(255),
    dh NUMBER,
    dirvienc VARCHAR(255),
    dirvieng FLOAT,
    dpt FLOAT,
    dsem VARCHAR(255),
    hloc VARCHAR(255),
    hr FLOAT,
    ides NUMBER,
    idmun NUMBER,
    lat FLOAT,
    lon FLOAT,
    nes VARCHAR(255),
    nhor NUMBER,
    nmun VARCHAR(255),
    prec FLOAT,
    probprec FLOAT,
    raf FLOAT,
    temp FLOAT,
    velvien FLOAT,
    INSERTD_AT TIMESTAMP_TZ
) ; 

GRANT SELECT ON TABLE IDENTIFIER('"CONAGUA_PRONOSTICO"."API_PRONOSTICO_CONAGUA_MX"."SERVICE_PRONOSTICO_POR_MUNICIPIOS_GZ"') TO ROLE IDENTIFIER('"PUBLIC"') WITH GRANT OPTION
GRANT INSERT ON TABLE IDENTIFIER('"CONAGUA_PRONOSTICO"."API_PRONOSTICO_CONAGUA_MX"."SERVICE_PRONOSTICO_POR_MUNICIPIOS_GZ"') TO ROLE IDENTIFIER('"PUBLIC"') WITH GRANT OPTION
GRANT UPDATE ON TABLE IDENTIFIER('"CONAGUA_PRONOSTICO"."API_PRONOSTICO_CONAGUA_MX"."SERVICE_PRONOSTICO_POR_MUNICIPIOS_GZ"') TO ROLE IDENTIFIER('"PUBLIC"') WITH GRANT OPTION
GRANT DELETE ON TABLE IDENTIFIER('"CONAGUA_PRONOSTICO"."API_PRONOSTICO_CONAGUA_MX"."SERVICE_PRONOSTICO_POR_MUNICIPIOS_GZ"') TO ROLE IDENTIFIER('"PUBLIC"') WITH GRANT OPTION


USE DATABASE CONAGUA_PRONOSTICO;
USE SCHEMA API_PRONOSTICO_CONAGUA_MX;


GRANT USAGE ON DATABASE CONAGUA_PRONOSTICO TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA CONAGUA_PRONOSTICO.API_PRONOSTICO_CONAGUA_MX TO ROLE PUBLIC;
GRANT USAGE ON DATABASE SERVICE_PRONOSTICO_POR_MUNICIPIOS_GZ TO ROLE PUBLIC;

GRANT ALL PRIVILEGES ON SCHEMA CONAGUA_PRONOSTICO.API_PRONOSTICO_CONAGUA_MX TO ROLE PUBLIC;


GRANT ROLE PUBLIC TO USER DATA360;

GRANT USAGE ON WAREHOUSE DATA_360 TO ROLE PUBLIC;

CREATE WAREHOUSE DATA_360
    WITH
        WAREHOUSE_SIZE = 'SMALL'
        AUTO_SUSPEND = 300
        AUTO_RESUME = TRUE
        MIN_CLUSTER_COUNT = 1
        MAX_CLUSTER_COUNT = 1
        SCALING_POLICY = 'STANDARD';

--CREAR VIEW, CONTIENE LOS DATOS MAS RECIENTES DEL PUNTO 3
CREATE VIEW CONAGUA_PRONOSTICO.API_PRONOSTICO_CONAGUA_MX.DATA_PRONOSTICO_MUNICIPIO_version_current AS
SELECT *
FROM CONAGUA_PRONOSTICO.API_PRONOSTICO_CONAGUA_MX.DATA_PRONOSTICO_MUNICIPIO
WHERE INSERTD_AT = (
    SELECT MAX(INSERTD_AT) FROM CONAGUA_PRONOSTICO.API_PRONOSTICO_CONAGUA_MX.DATA_PRONOSTICO_MUNICIPIO 
);

--TABLAS Y VISTAS CREADAS 

--CONTIENE LOS DATOS MAS RECIENTES DEL PUNTO 3
SELECT * FROM CONAGUA_PRONOSTICO.API_PRONOSTICO_CONAGUA_MX.DATA_PRONOSTICO_MUNICIPIO_version_current;
-- CONTIENE LOS LOGS DE AIRFLOW
SELECT * FROM CONAGUA_PRONOSTICO.API_PRONOSTICO_CONAGUA_MX.AIRFLOW_TASK_LOGS 
-- UNION DE LA TABLA DATA_MUNICIPI Y PRONOSTICO_MUNICIPIOS
SELECT * FROM CONAGUA_PRONOSTICO.API_PRONOSTICO_CONAGUA_MX.DATA_PRONOSTICO_MUNICIPIO
--CONTIENE EL ANALISIS DE LOS PROMDEDIOS
SELECT * FROM CONAGUA_PRONOSTICO.API_PRONOSTICO_CONAGUA_MX.PRONOSTICO_MUNICIPIOS
-- CONTIENE LA DATA DESCARGADA DE LA API
SELECT * FROM CONAGUA_PRONOSTICO.API_PRONOSTICO_CONAGUA_MX.SERVICE_PRONOSTICO_POR_MUNICIPIOS_GZ 
-- CONTIENE UNA AUDITORIA DE LA TABLA SERVICE_PRONOSTICO_POR_MUNICIPIOS_GZ CON EL FIN DE ANALIZAR CUANTOS REGISTROS SE INSERTAN
SELECT * FROM CONAGUA_PRONOSTICO.API_PRONOSTICO_CONAGUA_MX.SERVICE_PRONOSTICO_AUDIT 
